name: Azure OpenAI Retirements Watcher

on:
  schedule:
    # Twice per day at 06:00 and 18:00 UTC
    - cron: "0 6,18 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache uv venv
        uses: actions/cache@v4
        with:
          path: .venv
          key: ${{ runner.os }}-uv-${{ hashFiles('requirements.txt') }}

      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$HOME/.rye/shims" >> $GITHUB_PATH
          echo "$HOME/.local/share/uv/bin" >> $GITHUB_PATH || true
          # Ensure uv on PATH
          echo "$(which uv || true)"
      
      - name: Create venv & install deps
        run: |
          uv venv .venv
          uv pip install -r requirements.txt

      - name: Run scraper
        run: |
          uv run scrape_ms_retirements.py

      - name: Publish rss.xml for GitHub Pages
        run: |
          mkdir -p docs
          cp output/rss.xml docs/rss.xml
          git add docs/rss.xml
          if [[ -n "$(git status --porcelain docs/rss.xml)" ]]; then
            git commit -m "chore: publish rss.xml to docs/ for Pages [skip ci]"
            git push
          fi

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          # Add the outputs and snapshot so diffs persist across runs
          git add -A output data || true
          if [[ -n "$(git status --porcelain output data)" ]]; then
            git commit -m "chore: update retirements CSV/RSS snapshot [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
